export const CHANGE_QUERY = 'CHANGE_QUERY';

export const GET_MOVIES_FAILURE = 'GET_MOVIES_FAILURE';
export const GET_MOVIES_REQUEST = 'GET_MOVIES_REQUEST';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
